# Generated by Django 5.1.6 on 2025-02-26 03:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Actif', 'Actif'), ('Passif', 'Passif'), ('Capitaux propres', 'Capitaux propres')], max_length=50)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Immobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_acquisition', models.DateField()),
                ('valeur_acquisition', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('duree_de_vie', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('taux_amortissement', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('valeur_residuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='PlanComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tresorerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flux', models.CharField(choices=[('Entrée', 'Entrée'), ('Sortie', 'Sortie')], max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ecriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('justificatif', models.CharField(blank=True, max_length=255, null=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures_credit', to='comptabilite.compte')),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures_debit', to='comptabilite.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('date_emission', models.DateField()),
                ('date_echeance', models.DateField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('etat', models.CharField(choices=[('Non payé', 'Non payé'), ('Partiellement payé', 'Partiellement payé'), ('Payé', 'Payé')], max_length=50)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='comptabilite.client')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='comptabilite.fournisseur')),
            ],
        ),
        migrations.AddField(
            model_name='compte',
            name='plan_comptable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='comptabilite.plancomptable'),
        ),
    ]
