# Generated by Django 5.1.6 on 2025-02-26 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_initial_data'),
    ]

    operations = [
    ]
